api_platform:
    title: 'Arbitration development project'
    description: 'CREATED BY TULQIN MUXTOROV'
    version: '0.0.2'

    #swager ui enable
    #    enable_entrypoint: false
    #    enable_swagger_ui: false
    #    enable_swagger: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    defaults:
        pagination_client_enabled: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true

    error_formats:
        json-problem:
            mime_types: [ 'application/problem+json' ]

        jsonld:
            mime_types: [ 'application/ld+json' ]

    collection:
        pagination:
            enabled_parameter_name: pagination # optional
            items_per_page_parameter_name: PerPage

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

        swagger_ui_extra_configuration:
            persistAuthorization: true
